### ISSUE TITLE
BBB1 Homework feedback 2019-2020

### ISSUE THREAD

**Issue by TCLamnidis** [TCLamnidis/BareBonesBash#7]
# `ln -s`
 - It is good practise to ALWAYS include the target of the command (even if it is just a `.`). Makes it more readable and less error-prone

# `grep -v`
To select al lines that do NOT match a pattern, you can use the`-v` option. No need to `grep -> diff`

# Code annotation
When annotating code, try to explain what the code does step by step, not only what it accomplishes. This makes it easier to understand your code when you look at it again in 2 years, but also for others.

**Comment by jfy133** [comment]
Additional:

# Code annotation

In ohterwords: why rather than what it does.

Also, make it as easy as possible for people to re-run a command. Don't include the prompt (we only do that so we can stop people from copy and pasting blindly ;)).

# Grep

You do'nt necessarily need to cat into it, can just run `grep 'pattern' file`

# Mistakes

always make sure the command words (e.g. copy and paste error `wget wget`

# Lazy

Don't need to run two `mkdir` commands for two folders

# comments

Are language specific! """ doesn't work in bash

**Comment by jfy133** [comment]
Added in https://github.com/TCLamnidis/BareBonesBash/commit/19b6d21bbb84244eea3c089ed4f5b1565347d518
